server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: studentsvc
          uri: lb://STUDENTSVC
          predicates:
            - Path=/**
        - id: academicsvc
          uri: lb://ACADEMICSVC
          predicates:
            - Path=/academic/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

