global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'commandes-service-job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      #- targets: ['192.168.1.5:9094'] # pas de localhost car on est dans un container
      - targets: ['commande-service:9094']
        labels:
          application: 'Service commandes (gestion des commandes)'