global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'student-service-job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      #- targets: ['192.168.1.5:9094'] # pas de localhost car on est dans un container
      - targets: ['studentsvc:9092']
        labels:
          application: 'Student api'

  - job_name: 'academic-service-job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      #- targets: ['192.168.1.5:9093'] # pas de localhost car on est dans un container
      - targets: ['academicsvc:9093']
        labels:
          application: 'Academic api'

  - job_name: 'registration-service-job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      #- targets: ['192.168.1.5:9095'] # pas de localhost car on est dans un container
      - targets: ['registrationsvc:9095']
        labels:
          application: 'Registration api'